spring:
  profiles:
    active: dev-h2
app:
  integrations:
     fixer:
        accessKey: 8b4aa49c8893dbd669305458fe4b373b
        url: http://data.fixer.io/api
        baseCurrency: EUR
        cron: 0 0/1 * * * *

